#!/bin/bash
 function disable_bt {
            echo "Detected Raspberry Pi 3...Disabling Bluetooth"
            if grep -q pi3-disable-bt "/boot/config.txt"; then
                echo 'Bluetooth Disabled'
            else
            echo 'dtoverlay=pi3-disable-bt' | sudo tee -a /boot/config.txt
                echo 'Bluetooth Disabled'
            fi
            sudo systemctl disable hciuart
           }


echo "Pi in the Sky - Installation"
echo "============================"
sleep 2

echo -e "\n\nInstalling git..."
sudo apt-get update
sudo apt-get install -y git
sleep 1

echo -e "\n\nSetting up serial ports..."
sleep 1
sudo systemctl mask serial-getty@ttyAMA0.service
sudo sed -e "s/console=serial0,115200//g" -i.backup /boot/cmdline.txt

echo -e "\n\nEnabling OneWire support..."
sleep 1
sudo raspi-config nonint do_onewire 0 #Default

rev=$(cat /proc/cpuinfo|grep Revision|awk -F: '$0=$2'|tr -d ' ' )

case "$rev" in
        a02082)
            disable_bt
            ;;
        a22082)
            disable_bt
            ;;
        *)
            echo "No bluetooth to disable"
            ;;
esac

read -rp $'\n\nDo you want to enable the Raspberry Pi camera? [Y,n]' choice 
case $choice in  
  n|N) ;;
  *) sudo raspi-config nonint do_camera 0 ;; 
esac

read -rp $'\n\nAre you using Lora transmisssion? [Y,n]' choice 
case $choice in  
  n|N) ;;
  *) sudo raspi-config nonint do_spi 0 ;; 
esac

read -rp $'\n\nEnable I2C? [Y,n]' choice
case $choice in  
  n|N) ;;
  *) sudo raspi-config nonint do_i2c 0 ;; 
esac

read -rp $'\n\nAre you using a USB Webcam[y,N]' choice 
case $choice in  
  n|N) ;;
  *) 
      echo "Installing fswebcam"
      echo "==================="
      sleep 3
      sudo apt-get install fswebcam ;; 
esac


echo -e "\n\nInstalling PiGPIO"
echo "================="
sleep 3

cd
wget abyz.co.uk/rpi/pigpio/pigpio.zip
unzip pigpio.zip
cd PIGPIO
make
sudo make install

echo -e "\n\nInstalling Wiring Pi"
echo "===================="
sleep 3
cd
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build

echo -e "\n\nInstalling SSDV"
echo "==============="
sleep 3
cd
git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install

echo -e "\n\nInstalling Pi in the Sky Software"
echo "================================="

cd
git clone https://github.com/PiInTheSky/pits.git
cd pits
./build

sudo mv /boot/pisky.txt /boot/pisky.txt.bak
echo "# General settings
disable_monitor=N
camera=Y

#RTTY Settings
payload=CHANGEME 		
frequency=434.250		
baud=300

#LORA Settings
LORA_Frequency_1=434.450	
LORA_Payload_1=CHANGEME		
LORA_Mode_1=1
LORA_image_packets_0=20

#Transmitted Images
low_width=320
low_height=240
high=2000
high_width=640
high_height=480
image_packets=4

#Locally Stored images
full_low_width=640
full_low_height=480
full_high_width=2592		
full_high_height=1944		
full_image_period=60
" | sudo tee -a /boot/pisky.txt

echo -e "\n\nInstall Complete"
echo -e "\nEdit your configuration by typing \"sudo nano /boot/pisky.txt\"\n"
