#!/bin/bash

echo -e "\n\nLora Gateway - Installation"
echo "============================"
sleep 2

echo -e "\n\nInstalling git..."
sudo apt-get update
sudo apt-get install -y git
sleep 1

sudo raspi-config nonint do_spi 0

echo -e "\n\nInstalling Wiring Pi"
echo "===================="
sleep 3
cd
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build

echo -e "\n\nInstalling SSDV"
echo "==============="
sleep 3
cd
git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install

sudo apt-get install -y libcurl4-openssl-dev libncurses5-dev

cd ~
git clone https://github.com/PiInTheSky/lora-gateway.git
cd lora-gateway
make

mv gateway-sample.txt gateway.txt

